### ISSUE TITLE
Feature Request: 'Give' Command without Restrictions.

### ISSUE THREAD

**Issue by InvalidSession** [decaprime/CommunityCommands#1]
In one of the previous updates the devs removed a few items from the in-built 'Give' command, I'm hoping that can be 'fixed' and restored to the way it once was, giving people the ability to spawn all items once again, including the Razer Hood/Cloaks as they are a sought after item and usually given as a Reward to players in my servers for certain milestones/events.

I believe ChatCommands had a working give command that allowed the spawning of all items still, though that mod is unlikely to be updated anytime soon, if at all.

**Comment by decaprime** [comment]
There's no restrictions on the give command and this should be completed as of a868babe8cff608bbf4b1b200de8d6076ef75d93
