### ISSUE TITLE
bloodpotion command does not restrict type to only BloodType enums

### ISSUE THREAD

**Issue by robotomist** [decaprime/CommunityCommands#12]
.bp, the Blood potion command doesn't have restriction on the int passed into the second parameter.

example:
![bugrep1](https://github.com/decaprime/CommunityCommands/assets/139401786/2703f920-4647-430c-a892-4346e7725a74)
This is not so much of a problem when a random number is passed. It just gives you a nameless blood potion and drinking it does not change blood type.

However if you choose an int that is some other prefab id in the game the command attempts to apply that prefab to the StoredBlood.bloodType. This makes the server freak out and spam this error:
error:
![bugrp2](https://github.com/decaprime/CommunityCommands/assets/139401786/421facce-e9cf-46f1-bef1-a428192ef22d)

**Comment by decaprime** [comment]
With the above fix:
![image](https://github.com/decaprime/CommunityCommands/assets/62450933/e3edde22-8e41-48bb-9b26-28b5834f7082)
