### ISSUE TITLE
Can't get the commands to work

### ISSUE THREAD

**Issue by Konahrik13** [decaprime/CommunityCommands#9]
I apologize as this likely isn't a bug or request but I cannot get any of the commands to work. I installed the mod and the dependencies it needed through the r2modman mod manager. When I opened the console and turned on commands through the "Adminauth" command I tried to do any of the commands and it didn't give a popup nor worked with typed out. Every time the console said there was no command going by .bloodpotion/.buff/.cd/etc, and trying it without the period didn't work either.

Is there something I needed to do before to make the commands this mod makes to work or ?

**Comment by decaprime** [comment]
CommunityCommands is a server mod. If you're installing through r2modmanager it's safe to assume you're not installing into a dedicated server. There's a tool that the V Rising community uses for this: https://v-rising.thunderstore.io/package/Mythic/ServerLaunchFix/ this let's you run server mods when starting from the game. 
You'll also need the dependencies Bloodstone, and VampireCommandFramework.

If you still need support you can use our community technical support forum at https://vrisingmods.com/discord
